version: '3.8'

services:

  bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html

      #- ./docker/uploads:/var/www/html/web/app/uploads
      # if the uploads data should be saved in the bind mount instead of the volume
      # comment the line below and uncomment the one above
      - uploads:/var/www/html/web/app/uploads 

    environment:
      APP_ENV: ${APP_ENV:-development}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
      DB_HOST: db
      DB_NAME: ${DB_NAME:-bedrock}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_PREFIX: ${DB_PREFIX:-wp_}
      WP_HOME: ${APP_URL:-http://localhost:8080}
      WP_SITEURL: ${APP_URL:-http://localhost:8080}/wp
    restart: always

  db:
    image: mariadb:10.7
    volumes:
      #- ./docker/database:/var/lib/mysql
      # if the db data should be saved in the bind mount instead of the volume
      # comment the line below and uncomment the one above 
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-bedrock}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - bedrock
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www/html
    restart: always

# if the db data should be saved in the bind mount instead of the volume
# comment the volume database
# same applies to the uploads if you want them to be in the bind mount
volumes:
  database:
  uploads: