version: '3.9'

services:
  bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - document_root:/var/www/html:rw
      - uploads:/var/www/html/web/app/uploads:rw

    env_file: .env

    environment:
      APP_ENV: ${APP_ENV:-development}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
    restart: always

  db:
    image: mariadb:10.7
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-bedrock}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - bedrock
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - document_root:/var/www/html:ro
    restart: always

# if the db data should be saved in the bind mount instead of the volume
# comment the volume database
# same applies to the uploads if you want them to be in the bind mount
volumes:
  document_root:
  database:
  uploads: